project:
  type: website
  output-dir: docs

website:
  title: "Sophia Chen ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_more.qmd
        text: About
      - href: reflection.qmd
        text: Reflection
      - href: cv.qmd
        text: CV
      - text: Portfolio
        menu:
          - href: projects/project1_park_polish.qmd
            text: Project 1 Park Polish
          - href: projects/project2_power_bi.qmd
            text: Project 2 Power BI
          - href: projects/project3_risk_management.qmd
            text: Project 3 Risk Management
      - href: https://github.com/chensophiasufei2-hub/my-eportfolio
        text: GitHub
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
