project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - about_more.qmd
    - cv.qmd
    - projects/*.qmd

website:
  title: "Sophia Chen ePortfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: index.qmd#about
      - text: "Background"
        href: index.qmd#background
      - text: "Skills"
        href: index.qmd#skills
      - text: "Portfolio"
        menu:
          - text: "Project Directory"
            href: projects/index.qmd
          - text: "Project 1 — Park Polish"
            href: projects/project1_park_polish.qmd
          - text: "Project 2 — Power BI"
            href: projects/project2_power_bi.qmd
          - text: "Project 3 — Risk Management"
            href: projects/project3_risk_management.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: index.qmd#contact

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: scripts.html
    toc: false
    smooth-scroll: true